name = "portfolio-cms-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# [vars]
# NOTION_TOKEN = "..."
# DATABASE_URI = "..."
# NOTION_DATABASE_ID_BLOG = "..."
# NOTION_DATABASE_ID_PROJECTS = "..."
# WEBHOOK_SECRET = "..."
